// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnLokx7wMdsgHPFZ9vctInZoRRKTiQCuM',
    appId: '1:1029566019666:android:255ca9e2f42b6b1b9a478b',
    messagingSenderId: '1029566019666',
    projectId: 'cupidum-dev',
    storageBucket: 'cupidum-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkpCrGaSp1grqKmM25akSzt_YtJzdlrQw',
    appId: '1:1029566019666:ios:e299cc167f6ff7ad9a478b',
    messagingSenderId: '1029566019666',
    projectId: 'cupidum-dev',
    storageBucket: 'cupidum-dev.appspot.com',
    iosClientId: '1029566019666-g1ihkdm38spdeok8f464sl4un7jdsjr0.apps.googleusercontent.com',
    iosBundleId: 'com.cupidum.app',
  );
}
